version: '3'

services:
  rental_db:
    image: mongo:3.6
    volumes:
      - ./mongo-data:/var/lib/mongodb
    ports:
      - "27018:27018"
  web:
    build: ./rental_web_admin
    volumes:
      - ./rental_web_admin:/rental_web_admin
    ports:
      - "8000:8000"
    depends_on:
      - rental_db
  crawler:
    build: ./rental_scraper
    volumes:
      - ./rental_scraper:/rental_scraper
    ports:
      - "8080:8080"
    depends_on:
      - rental_db

