# Generated by Django 2.0.2 on 2018-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerconfig',
            name='filter_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlerconfig',
            name='filter_neighborhood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlerconfig',
            name='filter_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlerconfig',
            name='filter_square_meters',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
