# Generated by Django 2.0.2 on 2018-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_admin', '0003_auto_20180225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerconfig',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
