# Generated by Django 2.0.2 on 2018-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_admin', '0004_crawlerconfig_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='pagination_regex',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='start_url',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_code',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_detail',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_item_list',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_neighborhood',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_next',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_price',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_square_meters',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_title',
        ),
        migrations.RemoveField(
            model_name='crawlerconfig',
            name='xpath_url',
        ),
    ]
